# Generated by Django 5.2.7 on 2025-10-27 23:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Club')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Liga')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carta_jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Jugador')),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DFC', 'Defensa Central'), ('LTI', 'Lateral Izquierdo'), ('LTD', 'Lateral Derecho'), ('MC', 'Medio Centro'), ('MI', 'Medio Izquierdo'), ('MD', 'Medio Derecho'), ('DC', 'Delantero Centro'), ('MP', 'Media Punta')], max_length=3, verbose_name='Posicion')),
                ('ritmo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Ritmo')),
                ('tiro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Tiro')),
                ('pase', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Pase')),
                ('regate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Regate')),
                ('defensa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Defensa')),
                ('fisico', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Físico')),
                ('activo', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.liga')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.liga'),
        ),
        migrations.AddField(
            model_name='club',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
        migrations.CreateModel(
            name='Equipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Equipo')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cartas', models.ManyToManyField(to='core.carta_jugador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
