# Generated by Django 5.2.7 on 2025-10-29 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carta_jugador_puntuacion_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos_portero',
            fields=[
                ('carta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.carta_jugador', verbose_name='Carta de Jugador')),
                ('salto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Salto')),
                ('parada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Parada')),
                ('saque', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Saque')),
                ('reflejos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Reflejos')),
                ('velocidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Velocidad Portero')),
                ('posicionamiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Posicionamiento Portero')),
            ],
        ),
    ]
