# Generated by Django 5.2.7 on 2025-11-01 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atributos_portero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta_jugador',
            name='parada',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Parada'),
        ),
        migrations.AddField(
            model_name='carta_jugador',
            name='posicionamiento',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Posicionamiento Portero'),
        ),
        migrations.AddField(
            model_name='carta_jugador',
            name='reflejos',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Reflejos'),
        ),
        migrations.AddField(
            model_name='carta_jugador',
            name='salto',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Salto'),
        ),
        migrations.AddField(
            model_name='carta_jugador',
            name='saque',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Saque'),
        ),
        migrations.AddField(
            model_name='carta_jugador',
            name='velocidad',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Velocidad Portero'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='defensa',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Defensa'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='fisico',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Físico'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='pase',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Pase'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='regate',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Regate'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='ritmo',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Ritmo'),
        ),
        migrations.AlterField(
            model_name='carta_jugador',
            name='tiro',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Tiro'),
        ),
        migrations.DeleteModel(
            name='Atributos_portero',
        ),
    ]
