# Generated by Django 5.2.7 on 2025-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carta_jugador_parada_carta_jugador_posicionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo_usuario',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos en Clasificación'),
        ),
    ]
