# Generated by Django 5.2.7 on 2025-11-10 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipo_usuario_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo_usuario',
            name='media',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Media del equipo'),
        ),
    ]
